name: Deploy to awardspace

on:
  push:
    branches:
      - main
jobs:
  build:
     name: servidor
     runs-on: ubuntu-server
     
     steps:
     -  name: Get latest code
        uses: actions/checkout@v3